### ISSUE TITLE
Build an error

### ISSUE THREAD

**Issue by MR-MaoJiu** [PonnamKarthik/FlutterRtmpPlublisher#15]
* What went wrong:
The Android Gradle plugin supports only Kotlin Gradle plugin version 1.3.10 and higher.
The following dependencies do not satisfy the required version:
project ':flutter_rtmp_publisher' -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.0

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

**Comment by C4st3ll4n** [comment]
how did u solved ? @MR-MaoJiu
