### ISSUE TITLE
Youtube live stream

### ISSUE THREAD

**Issue by Faiyyaz** [PonnamKarthik/FlutterRtmpPlublisher#9]
Hi,

Does this plugin supports youtube live streaming because i just tried using this plugin it shows every status correctly like connected, publishing and disconnected but my youtube live stream data is not getting updated only

**Comment by Faiyyaz** [comment]
Its working fine i had some issues with the api

**Comment by pojoba02** [comment]
Hey @Faiyyaz , how where you able to config rtmp with youtube cos mine config isn't working.
Thanks.

**Comment by Faiyyaz** [comment]
you need to pass rtmp url & stream name as a single string to the plugin and it will work
